### ISSUE TITLE
Create a service to get a demo url

### ISSUE THREAD

**Issue by roonyh** [fossasia/gci15.fossasia.org#170]
When contributors submit PRs we can use their own fork to get a preview. Which is at usually at  `http://<github-id>.github.io/gci15.fossasia.org`. Instead of manually adding the url we can make a service do it for us.

**Comment by roonyh** [comment]
I created a gci task for this work. I think it will be challenging and interesting :)  
https://codein.withgoogle.com/tasks/6145990943834112/

**Comment by roonyh** [comment]
I find something like this to be really useful. I thought this will be an interesting task to @fossasia/fossasia-gci-students  You have any feedback?

**Comment by namanyayg** [comment]
The new GCI looks so interesting!

I'm a bit confused _when_ the comment should be made. Is it only once, when the issue is opened? If that's so, I think adding https://developer.github.com/v3/activity/events/types/#issuesevent link somewhere will be helpful to clarify things.

**Comment by roonyh** [comment]
@namanyayg hey good to see you :) The comment should be made once when the pull request is made. I added some info on the linked task.

**Comment by namanyayg** [comment]
@roonyh Likewise :) 

Sweet! I think this is one really interesting task.

**Comment by PolBaladas** [comment]
Nice! Interesting task from the work automation perspective.

**Comment by yasoob** [comment]
So you want that when a student submits a pull request. A bot posts a
comment stating the url of the student's gh-pages' external url so that you
can quickly view the changes which he made. Right?

I want one or two clarifications. If a student pushes code to a `patch`
branch and submits a pull request using that branch then what? Those
changes would not be reflected on the gh-pages branch of the student's
repo. :) I hope I am making sense.

**Comment by roonyh** [comment]
> So you want that when a student submits a pull request. A bot posts a
> comment stating the url of the student's gh-pages' external url so that you
> can quickly view the changes which he made. Right?

Right! :+1:  

> I want one or two clarifications. If a student pushes code to a `patch`
> branch and submits a pull request using that branch then what? Those
> changes would not be reflected on the gh-pages branch of the student's
> repo. :) I hope I am making sense.

Good question! The bot should check if the base branch is `gh-pages` and only go ahead if it is.

**Comment by codethejason** [comment]
@roonyh Should the bot be created on this repository and if not should it be hosted on Github at all?

**Comment by codethejason** [comment]
Made the webhook and the service (https://github.com/codethejason/autoprresponder) and it's working for my fork (only gh-pages triggers the posting). This task took surprisingly long because Github's API is quite interesting; I actually needed to get the whole message body instead of the $_POST array. Only thing left to do is setting it up on the main repository, but I do not have permission for that.

**Comment by roonyh** [comment]
@codethejason That looks great! I will do the hosting. Let me check it.

**Comment by roonyh** [comment]
Very nice work. Webhook should be working. Will close this and see what others think.
