### ISSUE TITLE
Updating nav bar

### ISSUE THREAD

**Issue by Juanvulcano** [fossasia/gci15.fossasia.org#276]
Hi there guys, I've been thinking that the nav bar might need new colors.
I made this quick prototype of how it would look.
http://juanvhook.makes.org/goggles/juanvhooks-remix-of-gci15fossasiaorg-by-fossasia
What do you think about it?
:)

**Comment by Meta-Maxim** [comment]
@Juanvulcano I don't see any changes other than making the navbar blue. It should stay white so that the GCI ribbon stands out more, and also white fits more with Fossasia's theme. If it's blue then it's harder to see it when you are in a blue-ish colored section. Also when you hover over the navbar buttons they don't change to the correct color. Also the navbar shadow is still white and it clashes with the blue. I think the navbar is fine as it is. If it needs than update then it should be a new feature, not a color change.

**Comment by Juanvulcano** [comment]
@MaxBorsch It's just a prototype so that people can choose which color they prefer, it´s not a finished one. Using the right set of colors can really improve the design of a website. It's true that the current navbar it's just fine but it can always be improved. I personally think blue fits more with GCI theme, which is the purpose of the website. The proper colors for hovering can always be added to and changing blue-ish colored sections with other colors can really highlight the content. 
See attached examples.
![screenshot 2015-12-31 at 17 23 20](https://cloud.githubusercontent.com/assets/9177978/12068576/552a0a92-afe3-11e5-8a7e-8e95444e3cf3.png)
![screenshot 2015-12-31 at 17 22 25](https://cloud.githubusercontent.com/assets/9177978/12068586/a258f698-afe3-11e5-9385-11e2110bb74c.png)
