### ISSUE TITLE
Separate Social Media area into area for each service and improve styling

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci15.fossasia.org#395]
**Expected outcome**
- Different section for each service
- Different background color for each section area
- Do not add a tab for each section into the top menu
- lolak tweets should render links
- loklak tweets should load new tweets automatically on top

**Comment by jigyasa-grover** [comment]
- ~~Different section for each service~~
- ~~Different background color for each section area~~
- ~~Do not add a tab for each section into the top menu~~
- ~~lolak tweets should render links~~
- ~~loklak tweets should load new tweets automatically on top~~

@mariobehling I think all points have been covered now, should we close this ?

**Comment by aayusharora** [comment]
![2](https://cloud.githubusercontent.com/assets/12194719/12306126/4465a204-ba5e-11e5-9698-11cc8492ee4a.PNG)
@jig08 ,Are you sure ,I mean there are not different section with different background color for social media area. Also loclak tweets are not rendering ,currently working on the same.

**Comment by aayusharora** [comment]
All solved here  #422

**Comment by yasoob** [comment]
@aayusharora IMO we should not separate them into different areas just like all other sections because:
- Firstly, the widgets would look stretched.
- The document (html page) size would increase a lot and IMO we should not increase it further. It is already very large and requires a **lot** of scrolling.

@jig08 This issue is good to close.

**Comment by jigyasa-grover** [comment]
@yasoob +1.
Closing this Issue along-with PR #422 for now.
